use iivi;



CREATE TABLE IF NOT EXISTS serises(
id INTEGER AUTO_INCREMENT,
s_title VARCHAR(255) CHARACTER SET utf8,
s_use BOOL,
s_belong INTEGER  DEFAULT 0,
s_description BLOB,
s_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);



CREATE TABLE IF NOT EXISTS news(
id INT AUTO_INCREMENT,
n_titile VARCHAR(255) CHARACTER SET utf8,
n_link BLOB,
n_content BLOB,
n_modified_date DATETIME,
n_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);




CREATE TABLE IF NOT EXISTS products(
id INTEGER AUTO_INCREMENT,
p_path BLOB,
p_thumb BLOB,
p_series INTEGER,
p_description BLOB,
p_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS stores(
id INT AUTO_INCREMENT,
s_name VARCHAR(50)  CHARACTER SET utf8,
s_address BLOB,
s_area VARCHAR(10)  CHARACTER SET utf8,
s_link BLOB,
s_image BLOB,
s_description VARCHAR(255)  CHARACTER SET utf8,
s_join_date TIMESTAMP,
PRIMARY KEY(id)
);



CREATE TABLE IF NOT EXISTS exhibitions(
id INT AUTO_INCREMENT,
e_title VARCHAR(255),
e_address BLOB,
e_description BLOB,
PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS design(
id INT AUTO_INCREMENT,
d_description BLOB,
d_info BLOB,
PRIMARY KEY(id)
);


CREATE TABLE IF NOT EXISTS resoures(
id INT AUTO_INCREMENT,
r_path BLOB,
r_description BLOB,
r_belong varchar(12),
PRIMARY KEY(id)
);




SELECT * FROM stores;

